import type {
  Stock,
  Holding,
  WatchlistItem,
  NewsArticle,
  MarketIndex,
  Activity,
  AIInsight,
  Alert,
  PricePoint,
  TimeRange,
} from "@/types";

const rnd = (seed: number) => {
  let s = seed;
  return () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
};

export const MOCK_STOCKS: Stock[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Consumer Electronics",
    price: 232.14,
    change: 3.42,
    changePercent: 1.49,
    open: 229.5,
    previousClose: 228.72,
    dayHigh: 233.1,
    dayLow: 228.9,
    weekHigh52: 260.1,
    weekLow52: 164.08,
    volume: 48_320_000,
    avgVolume: 62_100_000,
    marketCap: 3_520_000_000_000,
    peRatio: 34.2,
    eps: 6.78,
    dividend: 0.96,
    dividendYield: 0.41,
    beta: 1.24,
    currency: "USD",
    ceo: "Tim Cook",
    employees: 164000,
    website: "apple.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1667px-Apple_logo_black.svg.png",
    description:
      "Designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories.",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corp.",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Software",
    price: 428.9,
    change: -2.14,
    changePercent: -0.5,
    open: 431.1,
    previousClose: 431.04,
    dayHigh: 432.4,
    dayLow: 427.2,
    weekHigh52: 468.35,
    weekLow52: 309.45,
    volume: 22_100_000,
    avgVolume: 25_400_000,
    marketCap: 3_180_000_000_000,
    peRatio: 36.4,
    eps: 11.78,
    dividend: 3.0,
    dividendYield: 0.7,
    beta: 0.9,
    currency: "USD",
    ceo: "Satya Nadella",
    employees: 228000,
    website: "microsoft.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1024px-Microsoft_logo.svg.png",
    description: "Develops and supports software, services, devices, and solutions worldwide.",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Semiconductors",
    price: 138.9,
    change: 4.87,
    changePercent: 3.63,
    open: 134.2,
    previousClose: 134.03,
    dayHigh: 139.5,
    dayLow: 133.8,
    weekHigh52: 152.89,
    weekLow52: 45.01,
    volume: 210_000_000,
    avgVolume: 240_000_000,
    marketCap: 3_410_000_000_000,
    peRatio: 68.2,
    eps: 2.03,
    dividend: 0.04,
    dividendYield: 0.03,
    beta: 1.68,
    currency: "USD",
    ceo: "Jensen Huang",
    employees: 29600,
    website: "nvidia.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Nvidia_logo.svg",
    description:
      "Provides graphics, compute and networking solutions with a focus on accelerated computing and AI.",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    exchange: "NASDAQ",
    sector: "Consumer Discretionary",
    industry: "Auto Manufacturers",
    price: 258.42,
    change: -6.11,
    changePercent: -2.31,
    open: 264.5,
    previousClose: 264.53,
    dayHigh: 265.9,
    dayLow: 256.8,
    weekHigh52: 299.29,
    weekLow52: 138.8,
    volume: 96_400_000,
    avgVolume: 88_000_000,
    marketCap: 822_000_000_000,
    peRatio: 63.9,
    eps: 4.05,
    dividend: 0,
    dividendYield: 0,
    beta: 2.3,
    currency: "USD",
    ceo: "Elon Musk",
    employees: 140000,
    website: "tesla.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_T_symbol.svg/1200px-Tesla_T_symbol.svg.png",
    description:
      "Designs, develops, manufactures, and sells electric vehicles and energy generation & storage systems.",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    exchange: "NASDAQ",
    sector: "Communication Services",
    industry: "Internet Content",
    price: 179.24,
    change: 1.02,
    changePercent: 0.57,
    open: 178.1,
    previousClose: 178.22,
    dayHigh: 180.1,
    dayLow: 177.8,
    weekHigh52: 191.75,
    weekLow52: 127.9,
    volume: 21_400_000,
    avgVolume: 24_300_000,
    marketCap: 2_210_000_000_000,
    peRatio: 24.1,
    eps: 7.44,
    dividend: 0.8,
    dividendYield: 0.45,
    beta: 1.05,
    currency: "USD",
    ceo: "Sundar Pichai",
    employees: 182000,
    website: "abc.xyz",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1024px-Google_2015_logo.svg.png",
    description:
      "Provides online advertising services, cloud computing, software, and hardware products.",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    exchange: "NASDAQ",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
    price: 214.5,
    change: 2.87,
    changePercent: 1.36,
    open: 212.1,
    previousClose: 211.63,
    dayHigh: 215.2,
    dayLow: 211.4,
    weekHigh52: 231.2,
    weekLow52: 145.32,
    volume: 34_100_000,
    avgVolume: 38_400_000,
    marketCap: 2_240_000_000_000,
    peRatio: 42.8,
    eps: 5.01,
    dividend: 0,
    dividendYield: 0,
    beta: 1.15,
    currency: "USD",
    ceo: "Andy Jassy",
    employees: 1500000,
    website: "amazon.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1024px-Amazon_logo.svg.png",
    description: "Retail sales of consumer products and subscriptions; AWS cloud infrastructure.",
  },
  {
    symbol: "META",
    name: "Meta Platforms Inc.",
    exchange: "NASDAQ",
    sector: "Communication Services",
    industry: "Internet Content",
    price: 585.32,
    change: 8.14,
    changePercent: 1.41,
    open: 578.4,
    previousClose: 577.18,
    dayHigh: 588.9,
    dayLow: 576.1,
    weekHigh52: 602.95,
    weekLow52: 313.66,
    volume: 12_300_000,
    avgVolume: 14_100_000,
    marketCap: 1_480_000_000_000,
    peRatio: 28.9,
    eps: 20.26,
    dividend: 2.0,
    dividendYield: 0.34,
    beta: 1.28,
    currency: "USD",
    ceo: "Mark Zuckerberg",
    employees: 71000,
    website: "meta.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/1024px-Meta_Platforms_Inc._logo.svg.png",
    description:
      "Builds products that help people connect and share through mobile devices, PCs, VR/AR headsets, and wearables.",
  },
  {
    symbol: "INFY",
    name: "Infosys Ltd.",
    exchange: "NSE",
    sector: "Technology",
    industry: "IT Services",
    price: 1892.4,
    change: 24.6,
    changePercent: 1.32,
    open: 1875.0,
    previousClose: 1867.8,
    dayHigh: 1898.0,
    dayLow: 1872.5,
    weekHigh52: 1998.0,
    weekLow52: 1351.55,
    volume: 5_200_000,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/1024px-Infosys_logo.svg.png",
    avgVolume: 7_400_000,
    marketCap: 7_850_000_000_000,
    peRatio: 27.8,
    eps: 68.05,
    dividend: 40,
    dividendYield: 2.11,
    beta: 0.55,
    currency: "INR",
    ceo: "Salil Parekh",
    employees: 317000,
    website: "infosys.com",
    description: "Global leader in next-generation digital services and consulting.",
  },
  {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    exchange: "NSE",
    sector: "Technology",
    industry: "IT Services",
    price: 4102.5,
    change: -18.4,
    changePercent: -0.45,
    open: 4125.0,
    previousClose: 4120.9,
    dayHigh: 4130.0,
    dayLow: 4092.0,
    weekHigh52: 4585.0,
    weekLow52: 3506.55,
    volume: 1_800_000,
    avgVolume: 2_400_000,
    marketCap: 14_800_000_000_000,
    peRatio: 30.1,
    eps: 136.32,
    dividend: 73,
    dividendYield: 1.78,
    beta: 0.48,
    currency: "INR",
    ceo: "K. Krithivasan",
    employees: 601546,
    website: "tcs.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/1024px-Tata_Consultancy_Services_Logo.svg.png",
    description: "Provides IT services, consulting and business solutions to global enterprises.",
  },
  {
    symbol: "RELIANCE",
    name: "Reliance Industries",
    exchange: "NSE",
    sector: "Energy",
    industry: "Oil & Gas",
    price: 1298.6,
    change: 12.8,
    changePercent: 0.99,
    open: 1284.0,
    previousClose: 1285.8,
    dayHigh: 1302.0,
    dayLow: 1281.0,
    weekHigh52: 1608.95,
    weekLow52: 1201.5,
    volume: 8_900_000,
    avgVolume: 12_100_000,
    marketCap: 17_800_000_000_000,
    peRatio: 24.5,
    eps: 52.98,
    dividend: 10,
    dividendYield: 0.77,
    beta: 1.02,
    currency: "INR",
    ceo: "Mukesh Ambani",
    employees: 347000,
    website: "ril.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Reliance_industries_logo.svg/1024px-Reliance_industries_logo.svg.png",
    description:
      "Diversified conglomerate with businesses across energy, petrochemicals, retail, and digital services.",
  },
  {
    symbol: "HDFCBANK",
    name: "HDFC Bank Ltd.",
    exchange: "NSE",
    sector: "Financial Services",
    industry: "Banks",
    price: 1745.3,
    change: -8.9,
    changePercent: -0.51,
    open: 1758.0,
    previousClose: 1754.2,
    dayHigh: 1760.0,
    dayLow: 1740.5,
    weekHigh52: 1880.0,
    weekLow52: 1363.55,
    volume: 6_300_000,
    avgVolume: 9_200_000,
    marketCap: 13_200_000_000_000,
    peRatio: 19.4,
    eps: 89.98,
    dividend: 19.5,
    dividendYield: 1.12,
    beta: 0.85,
    currency: "INR",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/HDFC_Bank_Logo.svg/1024px-HDFC_Bank_Logo.svg.png",
    ceo: "Sashidhar Jagdishan",
    employees: 213000,
    website: "hdfcbank.com",
    description: "India's largest private sector bank offering a wide range of financial services.",
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Semiconductors",
    price: 158.4,
    change: 5.24,
    changePercent: 3.42,
    open: 153.8,
    previousClose: 153.16,
    dayHigh: 159.2,
    dayLow: 152.9,
    weekHigh52: 227.3,
    weekLow52: 116.37,
    volume: 42_100_000,
    avgVolume: 48_000_000,
    marketCap: 256_000_000_000,
    peRatio: 128.5,
    eps: 1.23,
    dividend: 0,
    dividendYield: 0,
    beta: 1.72,
    currency: "USD",
    ceo: "Lisa Su",
    employees: 26000,
    website: "amd.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/AMD_logo.svg/1024px-AMD_logo.svg.png",
    description:
      "Global semiconductor company that develops high-performance computing and graphics products.",
  },
  {
    symbol: "NFLX",
    name: "Netflix Inc.",
    exchange: "NASDAQ",
    sector: "Communication Services",
    industry: "Entertainment",
    price: 748.9,
    change: -4.32,
    changePercent: -0.57,
    open: 754.1,
    previousClose: 753.22,
    dayHigh: 756.0,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Netflix_logo.svg/1024px-Netflix_logo.svg.png",
    dayLow: 745.8,
    weekHigh52: 795.4,
    weekLow52: 542.01,
    volume: 3_400_000,
    avgVolume: 4_100_000,
    marketCap: 320_000_000_000,
    peRatio: 44.9,
    eps: 16.68,
    dividend: 0,
    dividendYield: 0,
    beta: 1.32,
    currency: "USD",
    ceo: "Ted Sarandos",
    employees: 14000,
    website: "netflix.com",
    description:
      "Streaming entertainment service with TV series, documentaries, and feature films.",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    exchange: "NYSE",
    sector: "Financial Services",
    industry: "Banks",
    price: 245.6,
    change: 1.87,
    changePercent: 0.77,
    open: 243.8,
    previousClose: 243.73,
    dayHigh: 246.4,
    dayLow: 243.5,
    weekHigh52: 254.31,
    weekLow52: 179.2,
    volume: 8_200_000,
    avgVolume: 9_400_000,
    marketCap: 690_000_000_000,
    peRatio: 12.8,
    eps: 19.19,
    dividend: 5.0,
    dividendYield: 2.03,
    beta: 1.11,
    currency: "USD",
    ceo: "Jamie Dimon",
    employees: 316000,
    website: "jpmorganchase.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/JPMorgan_Chase_%26_Co._Logo_2008-present.svg/1024px-JPMorgan_Chase_%26_Co._Logo_2008-present.svg.png",
    description:
      "Leading global financial services firm and one of the largest banking institutions.",
  },
  {
    symbol: "BRKA",
    name: "Berkshire Hathaway Inc.",
    exchange: "NYSE",
    sector: "Financial Services",
    industry: "Insurance",
    price: 683450.0,
    change: 3200.0,
    changePercent: 0.47,
    open: 680250.0,
    previousClose: 680250.0,
    dayHigh: 685000.0,
    dayLow: 681500.0,
    weekHigh52: 706980.0,
    weekLow52: 520014.0,
    volume: 12000,
    avgVolume: 14500,
    marketCap: 1_410_000_000_000,
    peRatio: 19.2,
    eps: 35656.0,
    dividend: 0,
    dividendYield: 0,
    beta: 0.78,
    currency: "USD",
    ceo: "Warren Buffett",
    employees: 377000,
    website: "berkshirehathaway.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Berkshire_hathaway_logo.svg/1024px-Berkshire_hathaway_logo.svg.png",
    description:
      "Multinational conglomerate holding company with insurance, investment, and industrial operations.",
  },
  {
    symbol: "COIN",
    name: "Coinbase Global Inc.",
    exchange: "NASDAQ",
    sector: "Financial Services",
    industry: "Cryptocurrency",
    price: 178.5,
    change: 8.92,
    changePercent: 5.27,
    open: 170.2,
    previousClose: 169.58,
    dayHigh: 180.1,
    dayLow: 168.9,
    weekHigh52: 245.32,
    weekLow52: 62.01,
    volume: 21_300_000,
    avgVolume: 23_400_000,
    marketCap: 46_000_000_000,
    peRatio: null,
    eps: -1.2,
    dividend: 0,
    dividendYield: 0,
    beta: 2.15,
    currency: "USD",
    ceo: "Brian Armstrong",
    employees: 7500,
    website: "coinbase.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Coinbase_%28company%29_logo.svg/1024px-Coinbase_%28company%29_logo.svg.png",
    description:
      "Cryptocurrency exchange platform for buying, selling, and earning digital assets.",
  },
  {
    symbol: "GLD",
    name: "SPDR Gold Trust",
    exchange: "ARCA",
    sector: "Commodities",
    industry: "Precious Metals",
    price: 185.42,
    change: 2.14,
    changePercent: 1.17,
    open: 183.5,
    previousClose: 183.28,
    dayHigh: 186.2,
    dayLow: 183.1,
    weekHigh52: 212.5,
    weekLow52: 168.3,
    volume: 8_940_000,
    avgVolume: 7_200_000,
    marketCap: 72_000_000_000,
    peRatio: null,
    eps: 0,
    dividend: 0,
    dividendYield: 0,
    beta: -0.2,
    currency: "USD",
    ceo: "N/A - ETF",
    employees: 0,
    website: "spdrgoldshares.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Gold_symbol.svg/1024px-Gold_symbol.svg.png",
    description:
      "Exchange-traded fund that tracks the price of gold bullion. Provides exposure to physical gold without storage hassles.",
  },
  {
    symbol: "SLV",
    name: "iShares Silver Trust",
    exchange: "ARCA",
    sector: "Commodities",
    industry: "Precious Metals",
    price: 28.74,
    change: 0.89,
    changePercent: 3.19,
    open: 27.9,
    previousClose: 27.85,
    dayHigh: 29.1,
    dayLow: 27.8,
    weekHigh52: 32.5,
    weekLow52: 19.2,
    volume: 42_100_000,
    avgVolume: 38_900_000,
    marketCap: 14_800_000_000,
    peRatio: null,
    eps: 0,
    dividend: 0,
    dividendYield: 0,
    beta: 1.85,
    currency: "USD",
    ceo: "N/A - ETF",
    employees: 0,
    website: "ishares.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Silver_element.svg/1024px-Silver_element.svg.png",
    description:
      "Exchange-traded fund that holds physical silver bullion. Offers investors exposure to silver commodity prices.",
  },
  {
    symbol: "GOLD",
    name: "Barrick Gold Corporation",
    exchange: "NYSE",
    sector: "Materials",
    industry: "Metals & Mining",
    price: 89.35,
    change: 1.42,
    changePercent: 1.62,
    open: 87.8,
    previousClose: 87.93,
    dayHigh: 90.2,
    dayLow: 87.5,
    weekHigh52: 98.5,
    weekLow52: 56.2,
    volume: 6_234_000,
    avgVolume: 6_800_000,
    marketCap: 43_000_000_000,
    peRatio: 18.4,
    eps: 4.85,
    dividend: 0.9,
    dividendYield: 1.01,
    beta: 1.32,
    currency: "USD",
    ceo: "Mark Bristow",
    employees: 28000,
    website: "barrick.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Barrick_Gold_logo.svg/1024px-Barrick_Gold_logo.svg.png",
    description:
      "World-class mining company and leading producer of gold. Also produces copper and other minerals.",
  },
  {
    symbol: "SILVER",
    name: "Pan American Silver Corp.",
    exchange: "NASDAQ",
    sector: "Materials",
    industry: "Metals & Mining",
    price: 32.18,
    change: 1.05,
    changePercent: 3.37,
    open: 31.2,
    previousClose: 31.13,
    dayHigh: 32.8,
    dayLow: 31.0,
    weekHigh52: 42.1,
    weekLow52: 19.5,
    volume: 3_456_000,
    avgVolume: 4_200_000,
    marketCap: 6_800_000_000,
    peRatio: 28.5,
    eps: 1.13,
    dividend: 0.2,
    dividendYield: 0.62,
    beta: 2.12,
    currency: "USD",
    ceo: "Michael Timmins",
    employees: 6000,
    website: "panamericansilver.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Pan_American_Silver_Corp_logo.svg/1024px-Pan_American_Silver_Corp_logo.svg.png",
    description:
      "Leading primary silver producer with operations in the Americas. Also produces gold, copper, and other metals.",
  },
];

export const generateChartData = (symbol: string, range: TimeRange): PricePoint[] => {
  const stock = MOCK_STOCKS.find((s) => s.symbol === symbol) ?? MOCK_STOCKS[0];
  const points =
    range === "1D"
      ? 78
      : range === "1W"
        ? 35
        : range === "1M"
          ? 30
          : range === "6M"
            ? 180
            : range === "1Y"
              ? 252
              : range === "5Y"
                ? 260
                : 500;
  const seed = symbol.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  const rand = rnd(seed);
  const volatility = range === "1D" ? 0.004 : range === "1W" ? 0.012 : 0.02;
  let price = stock.price * (range === "1D" ? 0.995 : range === "5Y" ? 0.45 : 0.85);
  const data: PricePoint[] = [];
  const now = Date.now();
  const stepMs =
    range === "1D"
      ? 5 * 60_000
      : range === "1W"
        ? 4 * 60 * 60_000
        : range === "1M"
          ? 24 * 60 * 60_000
          : range === "6M"
            ? 24 * 60 * 60_000
            : range === "1Y"
              ? 24 * 60 * 60_000
              : range === "5Y"
                ? 7 * 24 * 60 * 60_000
                : 14 * 24 * 60 * 60_000;
  for (let i = points; i >= 0; i--) {
    price = price * (1 + (rand() - 0.48) * volatility);
    data.push({
      time: new Date(now - i * stepMs).toISOString(),
      price: Number(price.toFixed(2)),
      volume: Math.round(1_000_000 + rand() * 5_000_000),
    });
  }
  // Anchor last point to current
  data[data.length - 1].price = stock.price;
  return data;
};

export const MOCK_HOLDINGS: Holding[] = [
  {
    id: "h1",
    symbol: "AAPL",
    name: "Apple Inc.",
    quantity: 50,
    avgPrice: 178.4,
    purchaseDate: "2024-03-14",
    broker: "Zerodha",
    currentPrice: 232.14,
    invested: 8920,
    currentValue: 11607,
    pnl: 2687,
    pnlPercent: 30.12,
  },
  {
    id: "h2",
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    quantity: 40,
    avgPrice: 82.5,
    purchaseDate: "2024-01-22",
    broker: "Groww",
    currentPrice: 138.9,
    invested: 3300,
    currentValue: 5556,
    pnl: 2256,
    pnlPercent: 68.36,
  },
  {
    id: "h3",
    symbol: "INFY",
    name: "Infosys Ltd.",
    quantity: 100,
    avgPrice: 1620,
    purchaseDate: "2023-11-08",
    broker: "Zerodha",
    currentPrice: 1892.4,
    invested: 162000,
    currentValue: 189240,
    pnl: 27240,
    pnlPercent: 16.81,
  },
  {
    id: "h4",
    symbol: "TSLA",
    name: "Tesla Inc.",
    quantity: 20,
    avgPrice: 285.0,
    purchaseDate: "2024-06-02",
    broker: "Robinhood",
    currentPrice: 258.42,
    invested: 5700,
    currentValue: 5168.4,
    pnl: -531.6,
    pnlPercent: -9.33,
  },
  {
    id: "h5",
    symbol: "RELIANCE",
    name: "Reliance Industries",
    quantity: 60,
    avgPrice: 1420,
    purchaseDate: "2024-08-19",
    broker: "Zerodha",
    currentPrice: 1298.6,
    invested: 85200,
    currentValue: 77916,
    pnl: -7284,
    pnlPercent: -8.55,
  },
];

export const MOCK_WATCHLIST: WatchlistItem[] = MOCK_STOCKS.slice(0, 8).map((s, i) => ({
  id: `w${i}`,
  symbol: s.symbol,
  name: s.name,
  price: s.price,
  change: s.change,
  changePercent: s.changePercent,
  addedAt: new Date(Date.now() - i * 86400000).toISOString(),
}));

export const MOCK_INDICES: MarketIndex[] = [
  {
    symbol: "SPX",
    name: "S&P 500",
    value: 5842.31,
    change: 24.6,
    changePercent: 0.42,
    region: "US",
  },
  {
    symbol: "IXIC",
    name: "NASDAQ",
    value: 19218.4,
    change: -18.2,
    changePercent: -0.09,
    region: "US",
  },
  {
    symbol: "DJI",
    name: "Dow Jones",
    value: 42840.2,
    change: 108.4,
    changePercent: 0.25,
    region: "US",
  },
  {
    symbol: "NIFTY",
    name: "NIFTY 50",
    value: 24567.8,
    change: 89.3,
    changePercent: 0.36,
    region: "IN",
  },
  {
    symbol: "SENSEX",
    name: "BSE SENSEX",
    value: 80892.5,
    change: 245.8,
    changePercent: 0.31,
    region: "IN",
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    value: 98420,
    change: 1820,
    changePercent: 1.88,
    region: "CRYPTO",
  },
  {
    symbol: "ETH",
    name: "Ethereum",
    value: 3421.6,
    change: -42.8,
    changePercent: -1.23,
    region: "CRYPTO",
  },
  {
    symbol: "FTSE",
    name: "FTSE 100",
    value: 8148.2,
    change: 12.4,
    changePercent: 0.15,
    region: "EU",
  },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: "n1",
    title: "Nvidia unveils next-gen Blackwell Ultra GPUs, stock hits fresh high",
    summary:
      "The chipmaker's newest AI accelerators promise 2.5x performance improvements over the current H200 generation, sending shares up in pre-market trading.",
    source: "Reuters",
    category: "technology",
    url: "#",
    publishedAt: new Date(Date.now() - 3600_000).toISOString(),
    symbols: ["NVDA"],
    sentiment: "positive",
  },
  {
    id: "n2",
    title: "Fed signals two rate cuts in 2026 as inflation cools",
    summary:
      "Federal Reserve minutes indicate a dovish shift as core PCE hits the 2% target for the first time in three years.",
    source: "Bloomberg",
    category: "economy",
    url: "#",
    publishedAt: new Date(Date.now() - 7200_000).toISOString(),
    sentiment: "positive",
  },
  {
    id: "n3",
    title: "Tesla misses Q2 delivery estimates, shares slide 6%",
    summary:
      "Deliveries came in at 421,000 vs. consensus of 448,000 as competition from Chinese EV makers intensifies.",
    source: "CNBC",
    category: "business",
    url: "#",
    publishedAt: new Date(Date.now() - 10800_000).toISOString(),
    symbols: ["TSLA"],
    sentiment: "negative",
  },
  {
    id: "n4",
    title: "Bitcoin reclaims $98K as spot ETF inflows surge past $2B",
    summary:
      "Institutional demand for crypto exposure accelerates ahead of the anticipated regulatory framework announcement.",
    source: "CoinDesk",
    category: "crypto",
    url: "#",
    publishedAt: new Date(Date.now() - 14400_000).toISOString(),
    symbols: ["BTC"],
    sentiment: "positive",
  },
  {
    id: "n5",
    title: "Reliance Jio to launch AI-powered enterprise cloud in Q1 2026",
    summary:
      "Mukesh Ambani outlines a $10B investment plan to challenge AWS and Azure in the Indian enterprise market.",
    source: "Economic Times",
    category: "india",
    url: "#",
    publishedAt: new Date(Date.now() - 18000_000).toISOString(),
    symbols: ["RELIANCE"],
    sentiment: "positive",
  },
  {
    id: "n6",
    title: "JPMorgan raises full-year GDP forecast to 2.8%",
    summary:
      "Strong consumer spending and easing supply chain pressures underpin the upgraded outlook.",
    source: "Financial Times",
    category: "finance",
    url: "#",
    publishedAt: new Date(Date.now() - 21600_000).toISOString(),
    symbols: ["JPM"],
    sentiment: "positive",
  },
  {
    id: "n7",
    title: "Apple's Vision Pro 2 launches February with 40% lighter design",
    summary:
      "Second-generation headset targets mass market with a sub-$2,000 price point and improved eye-tracking.",
    source: "The Verge",
    category: "technology",
    url: "#",
    publishedAt: new Date(Date.now() - 25200_000).toISOString(),
    symbols: ["AAPL"],
    sentiment: "positive",
  },
  {
    id: "n8",
    title: "ECB holds rates steady, warns on wage-driven inflation",
    summary:
      "European Central Bank maintains a cautious stance as service-sector inflation remains sticky at 3.4%.",
    source: "Reuters",
    category: "global",
    url: "#",
    publishedAt: new Date(Date.now() - 28800_000).toISOString(),
    sentiment: "neutral",
  },
];

export const MOCK_ACTIVITY: Activity[] = [
  {
    id: "a1",
    type: "buy",
    symbol: "NVDA",
    description: "Bought 10 shares @ $138.20",
    amount: 1382,
    timestamp: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: "a2",
    type: "alert",
    symbol: "TSLA",
    description: "Price alert triggered: below $260",
    timestamp: new Date(Date.now() - 7200_000).toISOString(),
  },
  {
    id: "a3",
    type: "watch",
    symbol: "META",
    description: "Added to watchlist",
    timestamp: new Date(Date.now() - 10800_000).toISOString(),
  },
  {
    id: "a4",
    type: "sell",
    symbol: "AMD",
    description: "Sold 15 shares @ $155.80",
    amount: 2337,
    timestamp: new Date(Date.now() - 14400_000).toISOString(),
  },
  {
    id: "a5",
    type: "dividend",
    symbol: "INFY",
    description: "Dividend received ₹4,000",
    amount: 4000,
    timestamp: new Date(Date.now() - 86400_000).toISOString(),
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "al1",
    symbol: "AAPL",
    type: "price",
    condition: "above",
    value: 240,
    active: true,
    createdAt: new Date(Date.now() - 3 * 86400_000).toISOString(),
  },
  {
    id: "al2",
    symbol: "TSLA",
    type: "price",
    condition: "below",
    value: 250,
    active: true,
    createdAt: new Date(Date.now() - 86400_000).toISOString(),
    triggered: true,
  },
  {
    id: "al3",
    symbol: "NVDA",
    type: "rsi",
    condition: "above",
    value: 70,
    active: true,
    createdAt: new Date(Date.now() - 2 * 86400_000).toISOString(),
  },
  {
    id: "al4",
    symbol: "INFY",
    type: "volume",
    condition: "above",
    value: 10_000_000,
    active: false,
    createdAt: new Date(Date.now() - 5 * 86400_000).toISOString(),
  },
];

export const buildAIInsight = (symbol: string): AIInsight => {
  const stock = MOCK_STOCKS.find((s) => s.symbol === symbol.toUpperCase()) ?? MOCK_STOCKS[0];
  const bullish = stock.changePercent > 0;
  return {
    symbol: stock.symbol,
    companyName: stock.name,
    summary: `${stock.name} is a ${bullish ? "bullish" : "cautious"} position in the ${stock.sector} sector. Momentum is ${bullish ? "positive with strong volume support" : "consolidating after a recent pullback"}, and fundamentals remain ${stock.peRatio < 30 ? "attractively valued" : "priced for growth"}.`,
    businessOverview: stock.description ?? "",
    growthPotential: `Revenue growth is expected to compound at 12-18% annually driven by ${stock.industry.toLowerCase()} tailwinds. Margin expansion opportunities remain in the medium term.`,
    financialHealth: `Balance sheet is ${stock.marketCap > 500_000_000_000 ? "fortress-grade" : "healthy"} with strong free cash flow generation. Debt/equity ratios stay well within sector norms.`,
    fundamentalAnalysis: `P/E of ${stock.peRatio} vs sector median ~25. EPS of ${stock.eps} is trending upward. Dividend yield of ${stock.dividendYield}% provides a modest income cushion.`,
    technicalAnalysis: `Price is trading ${stock.price > stock.previousClose ? "above" : "below"} short-term moving averages. RSI is neutral (~55). MACD ${bullish ? "shows a bullish crossover" : "is flattening near the signal line"}.`,
    pros: [
      "Category-leading market position",
      "Strong operating margins and pricing power",
      "Robust R&D pipeline",
      "Institutional accumulation over the past quarter",
    ],
    cons: [
      "Elevated valuation multiples",
      "Sensitivity to macro rate cycles",
      "Competitive pressure from new entrants",
    ],
    riskScore: Math.round(30 + Math.abs(stock.beta * 25)),
    confidenceScore: bullish ? 76 : 58,
    recommendation: bullish
      ? stock.changePercent > 2
        ? "Strong Buy"
        : "Buy"
      : stock.changePercent < -2
        ? "Hold"
        : "Hold",
    targetPrice: Number((stock.price * (bullish ? 1.18 : 1.06)).toFixed(2)),
    futureOutlook: `12-month outlook is ${bullish ? "constructive" : "neutral"}. Watch upcoming earnings and sector rotation dynamics as key catalysts.`,
  };
};
