/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppStocksRouteImport } from './routes/_app.stocks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScreenerRouteImport } from './routes/_app.screener'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppNewsRouteImport } from './routes/_app.news'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppStocksSymbolRouteImport } from './routes/_app.stocks.$symbol'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppStocksRoute = AppStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenerRoute = AppScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppStocksSymbolRoute = AppStocksSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => AppStocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/news': typeof AppNewsRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/stocks': typeof AppStocksRouteWithChildren
  '/watchlist': typeof AppWatchlistRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/news': typeof AppNewsRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/stocks': typeof AppStocksRouteWithChildren
  '/watchlist': typeof AppWatchlistRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/screener': typeof AppScreenerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stocks': typeof AppStocksRouteWithChildren
  '/_app/watchlist': typeof AppWatchlistRoute
  '/_app/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/dashboard'
    | '/news'
    | '/portfolio'
    | '/profile'
    | '/reports'
    | '/screener'
    | '/settings'
    | '/stocks'
    | '/watchlist'
    | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/dashboard'
    | '/news'
    | '/portfolio'
    | '/profile'
    | '/reports'
    | '/screener'
    | '/settings'
    | '/stocks'
    | '/watchlist'
    | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/sitemap.xml'
    | '/_app/ai'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/news'
    | '/_app/portfolio'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/screener'
    | '/_app/settings'
    | '/_app/stocks'
    | '/_app/watchlist'
    | '/_app/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocks': {
      id: '/_app/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AppStocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screener': {
      id: '/_app/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof AppScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocks/$symbol': {
      id: '/_app/stocks/$symbol'
      path: '/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof AppStocksSymbolRouteImport
      parentRoute: typeof AppStocksRoute
    }
  }
}

interface AppStocksRouteChildren {
  AppStocksSymbolRoute: typeof AppStocksSymbolRoute
}

const AppStocksRouteChildren: AppStocksRouteChildren = {
  AppStocksSymbolRoute: AppStocksSymbolRoute,
}

const AppStocksRouteWithChildren = AppStocksRoute._addFileChildren(
  AppStocksRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewsRoute: typeof AppNewsRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScreenerRoute: typeof AppScreenerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStocksRoute: typeof AppStocksRouteWithChildren
  AppWatchlistRoute: typeof AppWatchlistRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNewsRoute: AppNewsRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppScreenerRoute: AppScreenerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStocksRoute: AppStocksRouteWithChildren,
  AppWatchlistRoute: AppWatchlistRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
